import type {Metadata} from "next";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {StyleProvider} from '@ant-design/cssinjs';
import {ProjectLayout} from "@/components/layout/ProjectLayout";
import './globals.css'
import Head from "next/head";
import {ConfigProvider} from "antd";
import {theme} from "@/lib/theme";

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AntdRegistry>
                    <ConfigProvider theme={theme}>
                        {children}
                    </ConfigProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
